# This is the configuration used to check the rubocop source code.
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'node_modules/**/*'
    - 'bin/**/*'
  UseCache: true
  CacheRootDirectory: ~

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 159

Metrics/BlockNesting:
  Max: 2

Metrics/BlockLength:
  Max: 1529

Layout/LineLength:
  Include:
    - 'app/**/*'
  Max: 120
  AllowURI: true

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Style/AndOr:
  EnforcedStyle: 'conditionals'

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Style/WordArray:
  MinSize: 3

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/HashSyntax:
  EnforcedStyle: 'ruby19'

Performance/Casecmp:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Alias:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/Next:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Lint/ToJSON:
  Enabled: false
