version: '3'
services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: codnasq_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
