version: '3'
services:
  web:
    build: .
    environment:
      - RAILS_ENV=production
    command: bash -c "RUBYOPT='-W:no-deprecated -W:no-experimental' bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
